In [59]:
import pandas as pd
import numpy as np

In [60]:
for_empresas = pd.read_excel(r'C:\Users\jober\Downloads\formacion_empresas_marzo_25.xlsx', sheet_name='Sheet1')
empresas = pd.read_excel(r'C:\Users\jober\Downloads\formacion_empresas_marzo_25.xlsx', sheet_name='Formulario')

In [61]:
for_empresas.columns

Index(['Adjudicado', 'Tratamiento de Datos', 'Fecha de Registro',
       'Nombre Completo del Participante', 'Tipo de Documento',
       'Número de Documento', 'CARGO', 'Rango de Edad', 'Género',
       'Correo electrónico @', 'Último nivel de estudio aprobado',
       'Tipo de población', '¿Tiene alguna discapacidad?',
       'Indique el nombre de la capacitación en el que participaras.',
       'INDIQUE NOMBRE DE LA EMPRESA'],
      dtype='object')

In [62]:
empresas = empresas.merge(for_empresas[['Número de Documento','Fecha de Registro']], on='Número de Documento', how='left')

In [63]:
empresas['Fecha de REGISTRO'] = empresas['Fecha de Registro']
empresas = empresas.drop(['Fecha de Registro','HORA'], axis=1)

In [64]:
# Get the column you want to move
col_to_move = empresas.columns[6]  # index starts at 0

# Reorder the columns
new_order = [col for col in empresas.columns if col != col_to_move] + [col_to_move]

# Reassign the DataFrame with the new column order
empresas = empresas[new_order]

In [74]:
empresas['mes'] = pd.to_datetime(empresas['Fecha de REGISTRO']).dt.month
empresas['año'] = pd.to_datetime(empresas['Fecha de REGISTRO']).dt.year

In [75]:
empresas.head()

,Adjudicado,"Para prestarte un mejor servicio y cumplir nuestras funciones, la Alcaldía Distrital de Barranquilla tratará tus datos personales conforme a la Ley 1581 de 2012. Conoce tus derechos y cómo ejercerlos en nuestra Política de \n Tratamiento de Datos en: www.barranquilla.gov.co/politica-de-tratamiento-de-datos. Se informa que es de carácter voluntario responder preguntas que tratan sobre Datos Sensibles. Tenga en cuenta que, si el formulario corresponde a la inscripción \n de un beneficio, el diligenciamiento de este no representa la asignación del mismo, ya que una vez finalizada, será sujeta a revisión y verificación por parte de la entidad; pero si el formulario obedece a una encuesta, el uso de los datos estará limitado a la finalidad de la misma.",Fecha de REGISTRO,Nombre,Tipo de Documento,Número de Documento,CARGO,Ranfo de Edad,Género,Correo electrónico @,Último nivel de estudio aprobado,Tipo de población,¿Tiene alguna discapacidad?,capacitacion,empresa,mes,año
0,NO,Sí Acepto,2025-03-14 15:28:41,Yanoldis de la cruz,CC - CEDULA DE CIUDADANIA,44156633,Supervisora,ENTRE 29-59,Femenino,Yanoldis23@gmail.com,Técnico / Tecnólogo,Ninguno,Ninguno,Taller de inclusión y discapacidad y abordaje ...,Servicios integrados NP SAS,3.0,2025.0
1,NO,Sí Acepto,2025-03-14 15:29:15,Carlos Rafael Perez Olivera,CC - CEDULA DE CIUDADANIA,1052075153,Supervisor,ENTRE 29-59,Masculino,calidad.aseomtto@lavianda.co,Técnico / Tecnólogo,Ninguno,Ninguno,Taller de inclusión y discapacidad y abordaje ...,Servicios integrados NP SAS,3.0,2025.0
2,NO,Sí Acepto,2025-03-14 15:29:29,Luis Hernando Lozano marino,CC - CEDULA DE CIUDADANIA,72264629,Supervisor,ENTRE 29-59,Masculino,luher24@hotmail.com,Bachiller,Ninguno,Ninguno,Taller de inclusión y discapacidad y abordaje ...,Servicios integrados NP SAS,3.0,2025.0
3,NO,Sí Acepto,2025-03-14 15:29:35,fredys contreras carbal,CC - CEDULA DE CIUDADANIA,72274889,supervisor,ENTRE 15-28,Masculino,fredyjuniorcontrera@gmail.comn,Profesional,Ninguno,Ninguno,Taller de inclusión y discapacidad y abordaje ...,Servicios integrados NP SAS,3.0,2025.0
4,NO,Sí Acepto,2025-03-14 15:30:06,Tania isabel Toledo Gonzalez,CC - CEDULA DE CIUDADANIA,1045733549,Supervisor,ENTRE 29-59,Femenino,Ttoledogonz@hotmail.com,Maestría / Especialización,Ninguno,Ninguno,Taller de inclusión y discapacidad y abordaje ...,Servicios integrados NP SAS,3.0,2025.0

# REPORTE CONTRATADOS GERENCIA CIUDAD

In [79]:
empresas[empresas['mes']==3.0].pivot_table(index='empresa', columns='Género', aggfunc='size', fill_value=0)

Género                               Femenino  Masculino
empresa
CENTRO INCA                                22        157
Corporación Tecnológica Indoamérica         0         30
DOLMEN                                     20          6
Gralco                                      8          5
SERVICIOS DE ALIMENTACION LA VIANDA         0          2
Servicios integrados NP SAS                 5          4
TAMARA IMAGENES DIAGNOSTICAS SAS           24          7